name: Rest Tests

on: [push]

jobs:

  tests:
    name: "Rest Api Tests"
    runs-on: ubuntu-18.04

    container:
      image: python:latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing all dependencies
        run: |
            pip install --user -r requirements.txt
      - name: Run tests
        run: |
            echo "Running tests..."
            python -m pytest api/tests/*


